# Configuration for CryLo-daemon
# Syntax: any command line option may be specified as 'clioptionname=value'.
#         Boolean options such as 'no-igd' are specified as 'no-igd=1'.
# See 'CryLo-daemon --help' for all available options.

data-dir=/var/lib/crylo
log-file=/var/log/crylo/CryLo-daemon.log
log-level=0
